accounts/urls.py
"""
By default, django.contrib.auth includes these views:

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']

"""
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from accounts import forms
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            authentication_form=forms.CustomUserAuthenticationForm
        ),
    ),
    path(
        'create/',
        views.CreateAccountView.as_view(),
        name="create_account"
    ),
    path(
        'confirm/',
        views.ConfirmAccountRequestedView.as_view(),
        name="confirm_account_requested"
    ),
    path(
        'confirm_email/<uidb64>/<token>/',
        views.ConfirmEmailView.as_view(),
        name="confirm_email"
    ),
    path(
        'change/',
        views.ChangeAccountView.as_view(),
        name="change"
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.CustomPasswordResetConfirmView.as_view(
            form_class=forms.CustomUserPasswordSetForm
        ),
        name="password_reset_confirm"
    ),
    path(
        'reset/done',
        views.CustomPasswordResetCompleteView.as_view(),
        name="custom_password_reset_done"
    ),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            form_class=forms.CustomUserPasswordResetForm
        ),
        name="password_reset"
    ),
    path(
        'inactive/',
        views.AccountInactiveView.as_view(
        ),
        name="inactive"
    ),
    # path(
    #     'login_with_google/',
    #     views.LoginWithGoogleView.as_view(),
    #     name="login_with_google"
    # ),
    # path(
    #     'login_with_google/callback/',
    #     auth_views.LoginWithGoogleViewCallback.as_view(),
    #     name="login_with_google_callback"
    # ),
    path(
        'activate/<uidb64>/<token>/',
        views.ActivateAccountView.as_view(),
    ),
    re_path(
        'resend/(?P<uidb64>[0-9A-Za-z_\-]+)/$',
        views.ResendEmailConfirmationLinkView.as_view(),
        name="resend_token"
    ),
]

chem/urls.py
# noinspection PyInterpreter,PyPackageRequirements,PyPackageRequirements,PyInterpreter
from django.urls import path
from . import views

app_name = 'chem'

urlpatterns = [
    path(
        "search/",
        views.ChemicalSearchView.as_view(),
        name="search"
    ),
    path(
        "search/results/",
        views.ChemicalSearchResultsAJAXView.as_view(),
        name="search_results"
    ),
    path(
        "blend/",
        views.ChemicalBlendView.as_view(),
        name="blend"
    ),
    path("detail/<int:pk>/", views.ChemicalDetail.as_view(), name='detail'),
    path("download/<int:pk>/", views.DownloadChemCSVToClient.as_view(),
         name='download'
    ),
    path(
        "download_chem_subm_tmpl",
         views.DownloadChemSubmissionTemplate.as_view(),
         name='download_chem_subm_tmpl'
    ),
    path(
        "download_blend_subm_tmpl",
         views.DownloadBlendSubmissionTemplate.as_view(),
         name='download_blend_subm_tmpl'
    ),
    path(
        "submit_chem",
        views.ChemicalSubmissionFormView.as_view(),
        name='submit_chem'
    ),
    path(
        "submit_blend", views.BlendSubmissionFormView.as_view(),
        name='submit_blend'
    ),
    path(
        "submit_data_success",
        views.SubmitDataSuccessView.as_view(),
        name='submit_data_success'
    ),
]

accounts/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from rest_framework.authtoken.models import Token

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    FIELD_OF_WORK_CHOICES = [
        ('', 'Field of Work'),
        ('industry', 'Industry'),
        ('private_consulting', 'Private Consulting'),
        ('academia', 'Academia/Education'),
        ('research', 'Research'),
        ('government', 'Government Agency'),
        ('nonprofit_org', 'Non-profit Organization'),
        ('other', 'Other'),
    ]

    username = None
    email = models.EmailField(
        _('Email Address'),
        unique=True,
    )

    affiliation = models.CharField(
        _('Organization/Company'),
        max_length=150,
    )

    field_of_work = models.CharField(
        _('Field of Work'),
        max_length=150,
        choices=FIELD_OF_WORK_CHOICES,
        default='',
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def save(self, *args, **kwargs):

        try:
            self.auth_token
            super().save(*args, **kwargs)
        except Token.DoesNotExist:
            super().save(*args, **kwargs)
            self.gen_api_token()

    def delete(self, *args, **kwargs):
        try:
            api_token = Token.objects.get(user=self)
            api_token.delete()
        except Exception as e:
            print(f'Could not find API token for user {self}')
            print(e)

        super().delete(*args, **kwargs)

    def make_active(self):
        self.is_active = True
        self.save()

    def gen_api_token(self):
        try:
            return Token.objects.get(user=self)
        except Exception as e:
            print(e)
            return Token.objects.create(user=self)



    def __str__(self):
        return self.email

accounts/forms.py
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, _unicode_ci_compare
)
from django.contrib.auth.forms import (
    AuthenticationForm, SetPasswordForm, PasswordResetForm
)
from django import forms
from django.contrib.auth import password_validation
from django.utils.translation import gettext, gettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Field, HTML, Button, Div


from .models import CustomUser
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
UserModel = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'placeholder': 'Password'
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'placeholder': 'Confirm Password'
            }
        ),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    eula_accepted = forms.BooleanField(
        label=_(
            'I am not a robot'
        ),
        required=True,
        widget=forms.CheckboxInput()
    )


    class Meta(UserCreationForm):
        model = CustomUser
        fields = (
            'first_name', 'last_name', 'email', 'affiliation', 'field_of_work'
        )
        field_order = [
            'first_name', 'last_name', 'email', 'affiliation', 'field_of_work'
        ]
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'First Name',
                    'autofocus': True
                }
            ),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Last Name'}
            ),
            'email': forms.TextInput(
                attrs={
                    'placeholder': 'Email Address',
                    'autofocus': False
                }
            ),
            'affiliation': forms.TextInput(
                attrs={'placeholder': 'Organization/Company'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'create-account-form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Register'))
        self.helper.form_class = 'form-group'
        self.helper.form_show_labels = True
        labeled_fields = ['eula_accepted']
        for field in self.fields.keys():
            if field not in labeled_fields:
                self.fields[field].label = False

class CustomUserChangeForm(UserChangeForm):
    password = None
    dummy_password = forms.CharField(
        label=_("Password"),
        strip=False,
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '***********',
                'readonly': True,
            }
        ),
    )

    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('email', 'affiliation', 'field_of_work')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-user-change-form'
        self.helper.form_method = 'post'
        self.helper.add_input(
            Button(
                'password reset button',
                'Reset Password',
                css_class='btn-warning',
                css_id='pwd-reset-btn',
                onclick="javascript:window.location.href = '../password_reset'",
            )
        )
        self.helper.add_input(
            Submit(
                'save-changes-btn', 'Save Changes', css_id='save-changes-btn'
            )
        )
        self.helper.form_class = 'form-group'
        self.helper.form_show_labels = True


class CustomUserAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.TextInput(
            attrs={'autofocus': True, 'placeholder': 'Email'}
        )
    )

    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'current-password',
                'placeholder': 'Password',
            }
        ),
    )

    class Meta:
        model = CustomUser
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-auth-form'
        self.helper.form_method = 'post'
        self.helper.add_input(
            Submit(
                'submit',
                'Sign in',
                css_class='btn-success'
            )
        )

        self.helper.form_class = 'form-group'
        self.helper.form_style = 'inline'
        self.helper.form_show_labels = False


class CustomUserPasswordResetForm(PasswordResetForm):

    email = forms.CharField(
        label=_("Email Address:"),
        required=True
    )

    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

    class Meta:
        model = CustomUser
        fields = ('email',)

    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        email_field_name = UserModel.get_email_field_name()
        active_users = UserModel._default_manager.filter(**{
            '%s__iexact' % email_field_name: email,
            'is_active': True,
        })
        return (u for u in active_users)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-auth-form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Send Reset Link'))
        self.helper.form_class = 'form-group'


class CustomUserPasswordSetForm(SetPasswordForm):

    class Meta:
        model = CustomUser

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-auth-form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-group'

accounts/templates/account_activated_email.html
  Hi {{ user.first_name }},

  Congratulations!

  Your account for the Feedstock to Function Tool has been approved.

  You can now log in here: {{'http://'|add:domain|add:'/accounts/login/'}}
  to access our full suite of tools and resources.

  ---
  The Feedstock to Function Team
  feedstock-to-function.lbl.gov

accounts/templates/account_confirmation_email.html
{% autoescape off %}
  Hi {{ user.first_name }},

  Thanks for requesting an account for the Feedstock to Function Tool.
  Please click on the following link to confirm your email address:
  {{ "http://"|add:domain|add:"/accounts/confirm_email/"|add:uid|add:"/"|add:token|add:"/" }}

  Once confirmed, the site administrator will review your account and
  notify you when it has been approved. This normally takes less than 24 hours.

  ---
  The Feedstock to Function Team
  feedstock-to-function.lbl.gov
{% endautoescape %}

accounts/templates/account_request_email.html
{% autoescape off %}

  A account for the Feedstock to Function Tool has been requested by
  a user with the following information:
  First Name: {{ user.first_name }}
  Last Name: {{ user.last_name }}
  E-mail: {{ user.email}}
  Affiliation: {{ user.affiliation}}
  Field of Work: {{ user.field_of_work}}

  To approve this account, click on the following link:
  {{ "http://"|add:domain|add:"/accounts/activate/"|add:uid|add:"/"|add:token|add:"/" }}

  Once confirmed, the site administrator will review your account and
  notify you once approved. This normally takes less than 24 hours.

  ---
  The Feedstock to Function Team
  feedstock-to-function.lbl.gov
{% endautoescape %}

accounts/templates/change_account.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
  <link rel="stylesheet" href="{% static 'accounts/stylesheets/styles.css' %}">
{% endblock %}

{% block content %}
  {% if request_type == "post" %}
    <br>
    <div class="d-flex justify-content-center">
      <div class="alert alert-success d-flex justify-content-center top-banner-alert">
        Your account settings have been updated!
      </div>
    </div>
  {% endif %}

  <div class="d-flex align-items-center justify-content-center"
       style="margin-top: 4%;">
    <div class="card" style="width: 27rem;">
      <div class="card-header" style="font-size:16px">
        Account Settings:
      </div>
      <div class="card-body">
        {% crispy form %}
        <input type="hidden" name="next" value="{{ next }}"/>
        {#                    TODO#}
        {# Assumes you setup the password_reset view in your URLconf #}
        </form>
        <!-- API key section -->
      <hr/>
        <label>API Key</label>
        <div class="form-control col-lg">
          {{ user.auth_token.key }}
          </div>
        <!-- end API key section -->
      </div>
    </div>
  </div>

{% endblock %}

accounts/templates/confirm_account_activated.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="d-flex align-items-center justify-content-center"
         style="margin-top: 10%;">
        <div class="card" style="width: 27rem;">
            <div class="card-header" style="font-size:16px">
                Account Activated!
            </div>
            <div class="card-body">
                <p>
                    The new user can now <a href="{% url 'login' %}">log in</a>
                    and access our tools and resources.
                </p>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/confirm_account_requested.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="d-flex align-items-center justify-content-center"
       style="margin-top: 10%;">
    <div class="card" style="width: 27rem;">
      <div class="card-header text-center" style="font-size:16px">
        Thanks for Registering!
      </div>
      <div class="card-body">
        <p>
          A confirmation email has been sent to
          the address you provided.
          Please follow the instructions to
          verify your email.
          A site administrator will then review
          your account and notify you once it has been
          approved.
          This usually takes less than 24 hours.
        </p>
      </div>
    </div>
  </div>

{% endblock %}

accounts/templates/confirm_email_success.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="d-flex align-items-center justify-content-center"
       style="margin-top: 10%;">
    <div class="card" style="width: 27rem;">
      <div class="card-header text-center" style="font-size:16px">
        Email Confirmed!
      </div>
      <div class="card-body">
        <p>
          Thanks for verifying your email address. Your account
          will be reviewed by a site administrator shortly and we'll
          notify you once approved. You will then be able to
          <a href="{% url 'login' %}">log in</a>
          to access our tools and resources.
        </p>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/create_account.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'accounts/stylesheets/styles.css' %}">
{% endblock %}

{% block content %}

    <div class="d-flex align-items-center justify-content-center"
         style="margin-top: 4%;">
        <div class="card" style="width: 27rem;">
            <div class="card-header" style="font-size:16px">
                Create New Account:
            </div>
            <div class="card-body">
                {% crispy form %}

                <input type="hidden" name="next" value="{{ next }}"/>
                {#                    TODO#}
                {# Assumes you setup the password_reset view in your URLconf #}
                </form>
            </div>
        </div>
    </div>

    <!-- EULA Modal -->
    <div class="modal fade" id="terms-modal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">
                        <strong>
                            LBNL End User License Agreement for Non-Commercial Research Use
                        </strong>

                    </h5>
                </div>
                <div class="modal-body">
                    <div id="eula-content"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary"
                            id="eula-modal-agree-btn"
                            data-dismiss="modal"
                    >
                        I agree
                    </button>
                </div>
            </div>
        </div>
    </div>
    {% block javascript %}
        <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

        <script type="text/javascript">
            // load the EULA content
            $('#id_eula_accepted').on('click', function () {
                $('#eula-content').load("{% static 'accounts/eula.html' %}")
                $('#terms-modal').modal('show');
              }
            )
        </script>
    {% endblock %}
{% endblock %}

accounts/templates/failed_account_activation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="d-flex align-items-center justify-content-center"
         style="margin-top: 10%;">
        <div class="card" style="width: 27rem;">
            <div class="card-header" style="font-size:16px">
                Error!
            </div>
            <div class="card-body">
                <p>
                    Invalid token. This confirmation link has expired.
                    has expired. Please click
                    <a href="{% url 'accounts:resend_token' uidb64 %}">
                        here
                    </a>
                    to generate a new one.
                </p>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/failed_email_confirmation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="d-flex align-items-center justify-content-center"
       style="margin-top: 10%;">
    <div class="card" style="width: 27rem;">
      <div class="card-header" style="font-size:16px">
        Error!
      </div>
      <div class="card-body">
        <p>
          Invalid token. This email confirmation link has expired.
          has expired. Please click
          <a href="{% url 'accounts:resend_token' uidb64 %}">
            here
          </a>
          to generate a new one.
        </p>
      </div>
    </div>
  </div>

{% endblock %}

accounts/templates/inactive_account.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="d-flex align-items-center justify-content-center"
       style="margin-top: 10%;">
    <div class="card" style="width: 27rem;">
      <div class="card-header text-center" style="font-size:16px">
        Inactive Account
      </div>
      <div class="card-body">
        <p>
          A confirmation email has been sent to
          the address you provided.
          Please follow the instructions to
          verify your email.
          A site administrator will then review
          your account and notify you once it has been
          approved.
          This usually takes less than 24 hours.
        </p>
      </div>
    </div>
  </div>

{% endblock %}