chem/urls.py
# noinspection PyInterpreter,PyPackageRequirements,PyPackageRequirements,PyInterpreter
from django.urls import path
from . import views

app_name = 'chem'

urlpatterns = [
    path(
        "search/",
        views.ChemicalSearchView.as_view(),
        name="search"
    ),
    path(
        "search/results/",
        views.ChemicalSearchResultsAJAXView.as_view(),
        name="search_results"
    ),
    path(
        "blend/",
        views.ChemicalBlendView.as_view(),
        name="blend"
    ),
    path("detail/<int:pk>/", views.ChemicalDetail.as_view(), name='detail'),
    path("download/<int:pk>/", views.DownloadChemCSVToClient.as_view(),
         name='download'
    ),
    path(
        "download_chem_subm_tmpl",
         views.DownloadChemSubmissionTemplate.as_view(),
         name='download_chem_subm_tmpl'
    ),
    path(
        "download_blend_subm_tmpl",
         views.DownloadBlendSubmissionTemplate.as_view(),
         name='download_blend_subm_tmpl'
    ),
    path(
        "submit_chem",
        views.ChemicalSubmissionFormView.as_view(),
        name='submit_chem'
    ),
    path(
        "submit_blend", views.BlendSubmissionFormView.as_view(),
        name='submit_blend'
    ),
    path(
        "submit_data_success",
        views.SubmitDataSuccessView.as_view(),
        name='submit_data_success'
    ),
]

tea_lca/urls.py
from django.urls import path
from tea_lca import views

app_name = 'tea_lca'

urlpatterns = [
    path("", views.TeaLcaToolView.as_view(), name="tea_lca_tool"),
    path(
        "analyze/<str:chem>", views.TeaLcaAnalyzeView.as_view(), name="analyze"
    ),
]

chem/views.py
from django.db.models import Q
from numpy import inf
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from collections import defaultdict
import re
import json
from urllib.parse import urlencode
from rdkit.Chem import MolToSmiles, MolFromSmiles
from rdkit.Chem.Draw import MolToFile
from django.urls import reverse
from django.shortcuts import render
import requests
from fuzzywuzzy import process
import csv
import copy
from django.contrib import messages
from django.shortcuts import render
from chem.serializers import ChemicalSerializer
from chem import (
    PRED_PROP_CODES,
    MIN_FUZZY_SEARCH_SCORE,
    MAX_FUZZY_SEARCH_RESULTS,
    FUZZY_SEARCH_SCORER,
    CHEM_STRUCT_IMG_DIR,
    ESTIMATORS_JOBLIB_DIR,
    DESCRIPTORS_DIR,
)

from chem.models import Chemical, ChemicalSynonym, PropertyEstimator
from chem.forms import (
    ChemicalSearchForm, ChemicalSubmissionForm, BlendSubmissionForm
)
from chem import CHEM_SUBMISSION_TEMPLATE, BLEND_SUBMISSION_TEMPLATE
from django.views.generic import (
    View, FormView, ListView, TemplateView, DetailView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.http import FileResponse, Http404, HttpResponseNotFound, \
    HttpResponse, \
    JsonResponse, HttpResponseRedirect
from django.utils.translation import ugettext as _
from fuzzywuzzy import process
from chem.serializers import ChemicalSerializer
import pandas as pd
from django.shortcuts import redirect
from django.urls import reverse_lazy
from mordred import Calculator, descriptors
from rdkit.Chem import MolFromSmiles, MolToSmiles
from pathlib import Path
import regex as re
import logging

from chem.utils import pred_props_and_errs_of_smiles, kelvin_to_celsius

# config logger
logger = logging.getLogger(__name__)
handler = logging.StreamHandler()
formatter = logging.Formatter(
    '[%(asctime)s %(levelname)s %(name)s] %(message)s', datefmt='%m-%d %H:%M'
)
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)


class DownloadChemCSVToClient(LoginRequiredMixin, View):

    def get(self, request, pk, *args, **kwargs):

        chem = Chemical.objects.get(pk=pk)
        dict = ChemicalSerializer(chem).data
        df = pd.DataFrame.from_dict(dict, orient='index').T
        csv = pd.DataFrame.to_csv(df, index=False)
        try:
            # with open(fpath, 'rb') as f:
            #     file_data = f.read()
            response = HttpResponse(
                csv, content_type='application/octet-stream'
            )
            response['Content-Disposition'] = \
                f'attachment; filename = "chemical_pk_{pk}.csv"'

        except IOError:
            # handle case where file does not exist
            response = HttpResponseNotFound(
                f'<h2>File does not exist</h2>'
            )

        return response


class DownloadChemSubmissionTemplate(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            # with open(fpath, 'rb') as f:
            #     file_data = f.read()
            print('template')
            print(CHEM_SUBMISSION_TEMPLATE)
            response = HttpResponse(
                CHEM_SUBMISSION_TEMPLATE,
                content_type='application/octet-stream'
            )
            # response = FileResponse(
            #     CHEM_SUBMISSION_TEMPLATE,
            #     content_type='application/octet-stream'
            # )
            response['Content-Disposition'] = \
                f'attachment; filename = "chemical_submission_template.csv"'
        except IOError:
            # handle case where file does not exist
            response = HttpResponseNotFound(
                f'<h2>File does not exist</h2>'
            )
        return response


class DownloadBlendSubmissionTemplate(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            response = HttpResponse(
                BLEND_SUBMISSION_TEMPLATE,
                content_type='application/octet-stream'
            )
            response['Content-Disposition'] = \
                f'attachment; filename = "blend_submission_template.csv"'
        except IOError:
            # handle case where file does not exist
            response = HttpResponseNotFound(
                f'<h2>File does not exist</h2>'
            )
        return response


class ChemicalDetail(LoginRequiredMixin, FormMixin, DetailView):
    model = Chemical
    form_class = ChemicalSearchForm
    template_name = 'chemical_detail.html'
    context_object_name = 'chem'

    @staticmethod
    def check_for_jmol_struct(smiles):
        jmol_base_url = "https://chemapps.stolaf.edu/jmol/jmol.php?model="
        # smiles = 'Cc1c([N+](=O)[O-])c(C)c([N+](=O)[O-])c(C(C)(C)C)c1[N+](=O)[O-]'
        req_url = f'{jmol_base_url}{smiles}'
        rv = requests.get(req_url)
        cont = str(rv.content)
        nih_err_substr = 'ERROR opening'
        jmol_err_substr = """
            The proxy server could not handle the request GET /jmol/jmol.php
        """
        if nih_err_substr in cont or jmol_err_substr in cont:
            return False
        return True

    def get_context_data(self, **kwargs):
        context = super(ChemicalDetail, self).get_context_data(**kwargs)
        context['form'] = self.form_class(
            initial={
                'search_type': self.kwargs.get('search_type'),
                'search_term': self.kwargs.get('search_term'),
            }
        )
        smiles = context['object'].smiles
        jmol_struct = ChemicalDetail.check_for_jmol_struct(smiles=smiles)
        if not jmol_struct:
            fn = f'struct_smiles_{smiles}.png'
            fp = Path(CHEM_STRUCT_IMG_DIR, fn)
            mol = MolFromSmiles(smiles)
            try:
                MolToFile(mol, fp)
            except (ValueError, IOError) as e:
                print('rdkit cant make image', e)
            context['struct_img'] = fn

        context['jmol_struct'] = jmol_struct
        return context

    def dispatch(self, *args, **kwargs):
        qdict = self.request.GET.dict()
        if 'search_type' in qdict and 'search_term' in qdict:
            qs = f'?{urlencode(qdict)}'
            return redirect(reverse('chem:search') + qs)
        return super(ChemicalDetail, self).dispatch(*args, **kwargs)


class ChemicalSearchResultsAJAXView(View):
    context_object_name = 'results'
    results_template_name = 'chemical_list.html'
    detail_template_name = 'chemical_detail_standalone.html'

    # TODO: split out a JSON view for retuning the JSON and other two for HTML
    def get(self, request, *args, **kwargs):
        params = {k: v[0] for k, v in dict(request.GET).items()}
        search_type = params['searchType']
        search_term = params['searchTerm']
        if search_type == 'smiles':
            rv = self.search_by_smiles(request, search_term)
        else:
            rv = self.search_non_smiles(request, params)
        return JsonResponse(rv)

    def search_non_smiles(self, request, params, *args, **kwargs):
        search_type = params['searchType']
        search_term = params['searchTerm']

        # First, get all search results for the provided search type and term.
        results = self.search_by_id(search_type, search_term)

        # Parse the search filters.
        filters = self._parse_property_filters(params)

        # Apply the search filters to the original results set.
        filtered_res = self._filter_results(results, filters)

        # Get the properties for which filters were used in the search
        filter_props = [k for k, v in filters.items()]

        context = {
            self.context_object_name: filtered_res,
            'search_type': search_type,
            'search_term': search_term,
            'filter_props': filter_props
        }
        res = render(request, self.results_template_name, context=context)
        html = res.content.decode('utf-8')
        return {'html': html}

    def _parse_property_filters(self, params):
        filters = defaultdict(dict)
        for k, v in params.items():
            # TODO: handle these checks using form validation in React
            if v != 'null':
                if k.endswith('Min'):
                    prop = f"{k.replace('Min', '')}"
                    filters[prop]['min'] = float(v)
                elif k.endswith('Max'):
                    prop = f"{k.replace('Max', '')}"
                    filters[prop]['max'] = float(v)
                elif k.endswith('AllowPreds'):
                    prop = f"{k.replace('AllowPreds', '')}"
                    if v == 'true':
                        filters[prop]['allow_preds'] = True
                    else:
                        filters[prop]['allow_preds'] = False
        return filters

    def _filter_results(self, results, filters, return_all_syns=False):
        filtered_results = []
        # Iterate over un-filtered Chemical results
        for r in results:
            # Get the Chemical object in case `r` is a ChemicalSynonym
            c = r.chem if isinstance(r, ChemicalSynonym) else r

            # Initialize flag for whether to keep a result (True) or filter it
            # out (False) based on property filters passed by caller.
            keep_result = True

            # Iterate over property filters and apply to current Chemical
            for prop, crit in filters.items():
                allow_preds = False
                if 'allow_preds' in crit:
                    allow_preds = crit['allow_preds']
                sfxs = ['exp', 'pred'] if allow_preds else ['exp']
                if 'min' in crit or 'max' in crit:
                    min_val = crit['min']
                    max_val = crit['max']

chem/templates/chemical_blend.html
{% extends "react_base.html" %}
{% block content %}
  {% block above_react_app %}
  {% endblock %}
  {{ block.super }}
{% endblock %}

chem/templates/chemical_detail.html
{% extends 'search.html' %}
{% load static %}
{% block search_results %}
  <div class="card my-1" style="width:100%; display: inline-block;">
    <div class="card-header text-center">
      <h5>Chemical Details</h5>
    </div>
    <div class="container">
      <table class="table table" width="100%">
        <tbody id="tablebody">
        <tr>
          <th>Structure</th>
          <td>
            {#            <div class="mb-0" style="margin-right: 380px; float: right;">#}
            <div class="mb-0" style="margin-right: 40%; float: right">
              {% if jmol_struct %}
                {% with base_url="https://chemapps.stolaf.edu/jmol/jmol.php?model=" %}
                  <script
                          type="text/javascript"
                          src="{{ base_url|add:chem.smiles|add:'&inline&height=300' }}"
                  >
                  </script>
                {% endwith %}
              {% else %}
                {#              <h5>No Structure Available</h5>#}
                <img src="{% static 'chem/img/structs/'|add:struct_img %}"
                     width="250px" height="250px"/>
              {% endif %}
            </div>
          </td>
        </tr>
        <tr>
          <th>SMILES ID</th>
          <td width="100%"> {{ chem.smiles }} </td>
        </tr>
        {% if chem.synonyms %}
          <tr>
            <th> Molecular Name(s)</th>
            <td>
              {% for synonym in chem.syns_list %}
                  {{ synonym }}; <br>
              {% endfor %}
            </td>
          </tr>
        {% endif %}
        {% if chem.formula %}
          <tr>
            <th> Molecular Formula</th>
            <td> {{ chem.formula }} </td>
          </tr>
        {% endif %}
        {% if chem.iupac %}
          <tr>
            <th>IUPAC Name</th>
            <td> {{ chem.iupac }} </td>
          </tr>
        {% endif %}
        {% if chem.inchi %}
          <tr>
            <th>InChiKey</th>
            <td>{{ chem.inchi }}</td>
          </tr>
        {% endif %}
        </tbody>
      </table>
      <br>
      <div class="card-footer text-center" style="vertical-align: middle;">
        <h5 style="vertical-align: middle;">Experimental Properties</h5>
      </div>
      <table class="table table-striped table-sm" style="margin-bottom: 10px;">
        <thead>
        <tr>
          <th style="width: 30%">Property</th>
          <th>Experimental Value</th>
          <th>Source(s)</th>
        </tr>
        </thead>
        <tbody id="tablebody">
        {% if chem.bp_exp %}
          {% with name="Boiling Point" %}
            {% with err=chem.bp_pred_abs_err exp=chem.bp_exp %}
              {% with srcs=chem.bp_exp_srcs exp=chem.bp_exp %}
                {% with estim=chem.bp_estimator %}
                  {% include "property_detail.html" %}
                {% endwith %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.mp_exp %}
          {% with name="Melting Point" %}
            {% with err=chem.mp_pred_abs_err exp=chem.mp_exp %}
              {% with srcs=chem.mp_exp_srcs exp=chem.mp_exp %}
                {% with estim=chem.mp_estimator %}
                  {% include "property_detail.html" %}
                {% endwith %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.fp_exp %}
          {% with name="Flash Point" %}
            {% with err=chem.fp_pred_abs_err exp=chem.fp_exp %}
              {% with srcs=chem.fp_exp_srcs exp=chem.fp_exp %}
                {% with estim=chem.fp_estimator %}
                  {% include "property_detail.html" %}
                {% endwith %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.hoc_exp %}
          {% with name="Heat of Combustion" %}
              {% with srcs=chem.hoc_exp_srcs exp=chem.hoc_exp %}
                  {% include "property_detail.html" %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.ysi_exp %}
          {% with name="Yield Sooting Index" %}
            {% with err=chem.ysi_pred_abs_err exp=chem.ysi_exp %}
              {% with srcs=chem.ysi_exp_srcs exp=chem.ysi_exp %}
                {% with estim=chem.ysi_estimator %}
                  {% include "property_detail.html" %}
                {% endwith %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        </tbody>
      </table>
      <div style="height: 50px;"></div>
      <div class="card-footer text-center" style="vertical-align: middle;">
        <h5 style="vertical-align: middle;">Predicted Properties</h5>
      </div>
      <table class="table table-striped table-sm" style="margin-bottom: 10px;">
        <thead>
        <tr>
          <th style="width: 30%">Property</th>
          <th>Predicted Value*</th>
          <th>Lower Error Bound*</th>
          <th>Upper Error Bound*</th>
        </tr>
        </thead>
        <tbody id="tablebody">
        {% if chem.bp_pred %}
          {% with name="Boiling Point" pred=chem.bp_pred %}
            {% with pred_err_low=chem.bp_pred_err_low %}
              {% with pred_err_up=chem.bp_pred_err_up %}
                {% include "property_detail.html" %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.mp_pred %}
          {% with name="Melting Point" pred=chem.mp_pred %}
            {% with pred_err_low=chem.mp_pred_err_low %}
              {% with pred_err_up=chem.mp_pred_err_up %}
                {% include "property_detail.html" %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.fp_pred %}
          {% with name="Flash Point" pred=chem.fp_pred %}
            {% with pred_err_low=chem.fp_pred_err_low %}
              {% with pred_err_up=chem.fp_pred_err_up %}
                {% include "property_detail.html" %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.hoc_pred %}
          {% with name="Heat of Combustion" pred=chem.hoc_pred %}
            {% with pred_err_low=chem.hoc_pred_err_low %}
              {% with pred_err_up=chem.hoc_pred_err_up %}
                {% include "property_detail.html" %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        {% if chem.ysi_pred %}
          {% with name="Yield Sooting Index" pred=chem.ysi_pred %}
            {% with pred_err_low=chem.ysi_pred_err_low %}
              {% with pred_err_up=chem.ysi_pred_err_up %}
                {% include "property_detail.html" %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        {% endif %}
        </tbody>
      </table>
{#      <div>#}
{#        <small>#}
{##}
{#        Portions of these results used high performance computing resources#}
{#        located at the Oak Ridge National Laboratory and provided by the#}
{#        Bioenergy Technologies Office of the U.S. Department of Energy.#}
{#        </small>#}
{#      </div>#}
      <div style="color:#f5411d">
        <small>

        *Predicted values and error bounds
        should be interpreted with caution, as algorithms
        are still under development.
        </small>
      </div>
    </div>
    <div class="text-center" style="margin: 50px">
      {% if chem.tea_lca_tool_alias %}
        <a href="{% url 'tea_lca:analyze' chem.tea_lca_tool_alias %}"
           class="btn btn-primary mr-3">
          Predict Life-cycle Costs & Emissions
        </a>
      {% endif %}
      <a href="{% url 'chem:download' chem.pk %}"
         class="btn btn-success">
        Download Data as CSV
      </a>
    </div>
  </div>
  </div>
{% endblock %}

chem/templates/chemical_list.html
{% block search_results %}
  {% if results %}
    <h3 class="text-center mt-0">Search Results</h3>
    <table class="table table-striped">
      <tr>
        <td colspan="2" class="text-center"
            style="font-style: italic; color: gray">
          Chemical Identifiers
        </td>
        <td colspan="5" class="text-center"
            style="font-style: italic; color: gray">
          Experimental Property Values
        </td>
      </tr>
      <tr>
        <th>SMILES</th>
        {% if search_type == 'smiles' or search_type == 'name' %}
          <th style="white-space: nowrap; width: 20px">
            Name(s)
          </th>
        {% endif %}
        {% if search_type == 'iupac' %}
          <th>IUPAC</th>
        {% endif %}
        {% if search_type == 'formula' %}
          <th>Molecular Formula</th>
        {% endif %}
        {% if search_type == 'inchi' %}
          <th>InChIKey</th>
        {% endif %}
        <th class="text-center">Melting <br> Point (°C)</th>
        <th class="text-center">Boiling <br> Point (°C)</th>
        <th class="text-center">Flash <br> Point (°C)</th>
        <th class="text-center">Yield Sooting <br> Index</th>
        <th class="text-center">Heat of <br>Combustion (kJ/g)</th>
      </tr>
      {% for object in results %}
        <tr>
          <td>
            {#          <td style="white-space: nowrap; width: 5px;">#}
            {% if object.smiles %}
              <a href="{% url 'chem:detail' pk=object.pk %}">
              {% if object.smiles|length > 30 %}
                <small>
                  {{ object.smiles|slice:"0:30"|add:'...' }}
                </small>
              {% else %}
                <small>
                  {{ object.smiles }}
                </small>
              {% endif %}
            {% endif %}
            </a>
          </td>
          {% if search_type == 'name' or search_type == 'smiles' %}
            {% if object.name %}
                <td>
                  <small>{{ object.names_str }}</small>
                </td>
          {% else %}
            <td class="text-center">-</td>
            {% endif %}
          {% endif %}
          {% if search_type == 'iupac' %}
            {% if object.iupac %}
              <td>{{ object.iupac }}</td>
            {% endif %}
          {% endif %}
          {% if search_type == 'formula' %}
            {% if object.formula %}
              <td>{{ object.formula }}</td>
            {% endif %}
          {% endif %}
          {% if search_type == 'inchi' %}
            {% if object.inchi %}
              <td>{{ object.inchi }}</td>
            {% endif %}
          {% endif %}
          {#            {% if 'mp' in filter_props %}#}
          {% if object.mp_exp and object.mp_exp|floatformat != 'nan' %}
            <td class="text-center">{{ object.mp_exp|floatformat }}</td>
          {% else %}
            <td class="text-center">-</td>
          {% endif %}
          {#            {% endif %}#}
          {#            {% if 'bp' in filter_props %}#}
          {% if object.bp_exp and object.bp_exp|floatformat != 'nan' %}
            <td class="text-center">{{ object.bp_exp|floatformat }}</td>
          {% else %}
            <td class="text-center">-</td>
          {% endif %}
          {% if object.fp_exp and object.fp_exp|floatformat != 'nan' %}
            <td class="text-center">{{ object.fp_exp|floatformat }}</td>
          {% else %}
            <td class="text-center">-</td>
          {% endif %}
          {#            {% endif %}#}
          {#            {% if 'ysi' in filter_props %}#}
          {% if object.ysi_exp and object.ysi_exp|floatformat != 'nan' %}
            <td class="text-center">{{ object.ysi_exp|floatformat }}</td>
          {% else %}
            <td class="text-center">-</td>
          {% endif %}
          {#            {% endif %}#}
          {#            {% if 'cn' in filter_props %}#}
          {% if object.hoc_exp and object.hoc_exp|floatformat != 'nan' %}
            <td class="text-center">{{ object.hoc_exp|floatformat }}</td>
          {% else %}
            <td class="text-center">-</td>
          {% endif %}
          {#            {% endif %}#}
        </tr>
        {#        {% endif %}#}
      {% endfor %}
    </table>
  {% endif %}
  {% if not results %}
    <div class="alert alert-danger text-center mt-0">
      No results matching query.
      Please try a different search term, search type or set of filters.
    </div>
  {% endif %}
{% endblock %}

chem/templates/chemical_search.html
{% extends "react_base.html" %}
{% block content %}
  {% block above_react_app %}
  {% endblock %}
  {{ block.super }}
{% endblock %}

chem/templates/data_submission_notify_email.html
{% autoescape off %}

  A user of the Feedstock to Function Tool has submitted data for a new
  molecule or blend.

  ---
  The Feedstock to Function Team
  feedstock-to-function.lbl.gov
{% endautoescape %}

chem/templates/property_detail.html
{% load mathfilters %}
{% block content %}
  <tr>
    <td> {{ name }} </td>
    {% if exp %}
      <td>
        {% if exp and exp|floatformat != 'nan' %}
          {{ exp|floatformat }}
          {% if name in "Boiling Point,Melting Point,Flash Point" %}
            &#176C
          {% endif %}
          {% if name in "Heat of Combustion" %}
            MJ/kg
          {% endif %}
        {% else %}
        {% endif %}
      </td>
    {% endif %}
    {% if exp %}
      <td>
        {% for src in srcs.all %}
          {% if src != 'nan' and exp|floatformat != 'nan' %}
            {% if not forloop.last %}
              <a href="{{ src.link }}" target="_blank">{{ src.name }},</a>
            {% else %}
              <a href="{{ src.link }}" target="_blank">{{ src.name }}</a>
            {% endif %}
          {% endif %}
        {% endfor %}
      </td>
    {% endif %}
    {% if pred %}
      <td>
      <span style="color: gray; font-style: italic">
    {% if pred and pred|floatformat != 'nan' %}
      {{ pred|floatformat }}
      {% if name in "Boiling Point,Melting Point,Flash Point" %}
        &#176C
      {% endif %}
      {% if name in "Heat of Combustion" %}
        MJ/kg
      {% endif %}
    {% else %}
    {% endif %}
      </span>
      </td>
      <td>
      <span style="color: gray; font-style: italic">
      {% if pred_err_low|floatformat != 'nan' %}
        {{ pred_err_low|floatformat }}
        {% if name in "Boiling Point,Melting Point,Flash Point" %}
          &#176C
        {% endif %}
        {% if name in "Heat of Combustion" %}
          MJ/kg
        {% endif %}
      {% else %}
      {% endif %}
      </span>
      </td>
      <td>
      <span style="color: gray; font-style: italic">
      {% if pred_err_low|floatformat != 'nan' %}
        {{ pred_err_up|floatformat }}
        {% if name in "Boiling Point,Melting Point,Flash Point" %}
          &#176C
        {% endif %}
        {% if name in "Heat of Combustion" %}
          MJ/kg
        {% endif %}
      {% else %}
      {% endif %}
      </span>
      </td>
    {% endif %}

  </tr>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
          integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
          crossorigin="anonymous"></script>
  <script>
    $(document).ready(function () {
      $('[data-toggle="popover"]').popover({html: true}).on('click',
        function (e) {
          e.preventDefault();
          return true;
        });
    });
    $('.popover-dismiss').popover({
      trigger: 'focus'
    })
  </script>
{% endblock %}

chem/templates/search.html
{% extends "base.html" %}
{% block content %}
{#  <div class="jumbotron py-3 mb-2">#}
{#    <h1 class="display-5 my-0">Explore Property Database</h1>#}
{#    <hr class="mt-2 mb-4">#}
{#    <form class="form" action="" method="GET">#}
{#      {{ form }}#}
{#      <button class="btn btn-success" type="submit">Search</button>#}
{#      </fieldset>#}
{#    </form>#}
{#  </div>#}
  {% block search_results %}
  {% endblock %}
{% endblock %}

chem/templates/submit_data_success.html
{% extends "base.html" %}

{% block content %}


  <div class="d-flex align-items-center justify-content-center"
       style="margin-top: 5%;">
    <div class="card" style="width: 27rem;">
      <div class="card-header text-center" style="font-size:16px">
        Data Submission Successful!
      </div>
      <div class="card-body">
        <p>
          Thanks for contributing to our database. Your data submission will
          improve the scope and quality of our tool!
        </p>
        <div class="d-flex flex-wrap justify-content-center my-1">
          <a class="btn btn-outline-secondary mx-3 mb-2"
             href="{% url 'chem:submit_chem' %}"
          >
            Submit New Chemical
          </a>
          <a class="btn btn-outline-secondary mx-3"
             href="{% url 'chem:submit_blend' %}"
          >
            Submit New Blend
          </a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}