about/urls.py
from django.urls import path
from about import views

app_name = 'about'

urlpatterns = [
    path("", views.AboutPage.as_view(), name="about"),
]

accounts/urls.py
"""
By default, django.contrib.auth includes these views:

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']

"""
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from accounts import forms
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            authentication_form=forms.CustomUserAuthenticationForm
        ),
    ),
    path(
        'create/',
        views.CreateAccountView.as_view(),
        name="create_account"
    ),
    path(
        'confirm/',
        views.ConfirmAccountRequestedView.as_view(),
        name="confirm_account_requested"
    ),
    path(
        'confirm_email/<uidb64>/<token>/',
        views.ConfirmEmailView.as_view(),
        name="confirm_email"
    ),
    path(
        'change/',
        views.ChangeAccountView.as_view(),
        name="change"
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.CustomPasswordResetConfirmView.as_view(
            form_class=forms.CustomUserPasswordSetForm
        ),
        name="password_reset_confirm"
    ),
    path(
        'reset/done',
        views.CustomPasswordResetCompleteView.as_view(),
        name="custom_password_reset_done"
    ),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            form_class=forms.CustomUserPasswordResetForm
        ),
        name="password_reset"
    ),
    path(
        'inactive/',
        views.AccountInactiveView.as_view(
        ),
        name="inactive"
    ),
    # path(
    #     'login_with_google/',
    #     views.LoginWithGoogleView.as_view(),
    #     name="login_with_google"
    # ),
    # path(
    #     'login_with_google/callback/',
    #     auth_views.LoginWithGoogleViewCallback.as_view(),
    #     name="login_with_google_callback"
    # ),
    path(
        'activate/<uidb64>/<token>/',
        views.ActivateAccountView.as_view(),
    ),
    re_path(
        'resend/(?P<uidb64>[0-9A-Za-z_\-]+)/$',
        views.ResendEmailConfirmationLinkView.as_view(),
        name="resend_token"
    ),
]

chem/urls.py
# noinspection PyInterpreter,PyPackageRequirements,PyPackageRequirements,PyInterpreter
from django.urls import path
from . import views

app_name = 'chem'

urlpatterns = [
    path(
        "search/",
        views.ChemicalSearchView.as_view(),
        name="search"
    ),
    path(
        "search/results/",
        views.ChemicalSearchResultsAJAXView.as_view(),
        name="search_results"
    ),
    path(
        "blend/",
        views.ChemicalBlendView.as_view(),
        name="blend"
    ),
    path("detail/<int:pk>/", views.ChemicalDetail.as_view(), name='detail'),
    path("download/<int:pk>/", views.DownloadChemCSVToClient.as_view(),
         name='download'
    ),
    path(
        "download_chem_subm_tmpl",
         views.DownloadChemSubmissionTemplate.as_view(),
         name='download_chem_subm_tmpl'
    ),
    path(
        "download_blend_subm_tmpl",
         views.DownloadBlendSubmissionTemplate.as_view(),
         name='download_blend_subm_tmpl'
    ),
    path(
        "submit_chem",
        views.ChemicalSubmissionFormView.as_view(),
        name='submit_chem'
    ),
    path(
        "submit_blend", views.BlendSubmissionFormView.as_view(),
        name='submit_blend'
    ),
    path(
        "submit_data_success",
        views.SubmitDataSuccessView.as_view(),
        name='submit_data_success'
    ),
]

ftf_web/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from ftf_web.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'ftf_web'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('api/v1/', include('api_v1.urls')),
    path("admin/", admin.site.urls),
    path("chem/", include("chem.urls")),
    path("about/", include("about.urls")),
    path("tea_lca/", include("tea_lca.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("allauth.urls")),
    # re_path('^api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tea_lca/urls.py
from django.urls import path
from tea_lca import views

app_name = 'tea_lca'

urlpatterns = [
    path("", views.TeaLcaToolView.as_view(), name="tea_lca_tool"),
    path(
        "analyze/<str:chem>", views.TeaLcaAnalyzeView.as_view(), name="analyze"
    ),
]

ftf_web/views.py
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView

def redirect(request, **kwargs):
    hostname = request.get_host().split(':')[0]
    return HttpResponseRedirect(f"https://{hostname}:{kwargs.get('var')}")

class HomePageView(TemplateView):
    template_name = 'home.html'

ftf_web/templates/base.html
{% load static %}
{% load icons %}

{#<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">#}
{#<link rel="stylesheet" href="{% static 'stylesheets/styles.css' %}">#}
<head>
  <!-- Font Awesome CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous"
  >
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
        crossorigin="anonymous">
  <script
          src="https://code.jquery.com/jquery-3.5.1.min.js"
          integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
          crossorigin="anonymous"></script>
  {#<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>#}
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
          integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
          integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
          crossorigin="anonymous"></script>
  <script>
    $(document).ready(function () {
      var url = window.location;
      // Will only work if string in href matches with location
      $('ul.nav a[href="' + url + '"]').parent().addClass('active');

      // Will also work for relative and absolute hrefs
      $('ul.nav a').filter(function () {
        return this.href == url;
      }).parent().addClass('active').parent().parent().addClass('active');
    });
  </script>
  {% block head %}
  {% endblock %}

</head>

<body>

<div class="container pr-0">
  <nav class="navbar navbar-expand-xl  navbar-light"
       style="background-color: #ffffff;">
    <img src="{% static 'img/ftf_img_only_logo.png' %}" height="40"
         alt="" style="margin-top: 0px; margin-right: 5px;">
    <a class="navbar-brand" style=" color: #5a5959;" href="/">
      Feedstock to Function Tool
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav ml-auto mr-0" style=" line-height: 40px;">
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'chem:search' %}">
            Molecule Explorer
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'chem:blend' %}">
            Explore Blends
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'tea_lca:tea_lca_tool' %}">
            Predict Costs & Emissions
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'about:about' %}">About</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-link auth-nav-item logged-in-auth-nav-item pr-0"
              style="border-right: 0px;">
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle ml-5"
                      type="button" id="user-dropdown-nav-item"
                      data-toggle="dropdown" aria-haspopup="true"
                      aria-expanded="false">
                {% icon 'user-circle' %}
                {#                <small>{{ user.get_username }}</small>#}
              </button>
              <div class="dropdown-menu dropdown-menu-right"
                   aria-labelledby="dropdownMenuButton">
                <p class="mt-0 mb-0 mx-4" style="color: gray">
                  <small>{{ user.email }}</small>
                </p>
                <hr class="mt-0">
                <a class="dropdown-item" href="{% url 'accounts:change' %}">
                  My Account
                </a>
                <a class="dropdown-item"
                   href="{% url 'logout' %}?next={{ request.path }}"
                   href="{% url 'logout' %}"
                >Sign out</a>
              </div>
            </div>
          </li>
        {% else %}
          <ul>
            <li class="nav-link auth-nav-item login-nav-item">
              <a href="{% url 'login' %}">
                <button class="btn btn-secondary"
                        type="button" id="login-btn"
                >
                  Sign in
                </button>
              </a>
            </li>
          </ul>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>
<hr style="margin-top: 0px">

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

{#<script>#}
{#$(".nav .nav-link").on("click", function(){#}
{#   $(".nav").find(".active").removeClass("active");#}
{#   $(this).addClass("active");#}
{#});#}
{#</script>#}
<div class="container mb-5" style="min-height: 65%">
  {% block content %}{% endblock %}
</div>
</body>
<footer>
  <hr class="my-2"/>
  <div class="container">
    <div class="row d-flex justify-content-center">
      <a href="https://niemeyer-research-group.github.io/">
        <img src="{% static 'img/osu.png' %}" height="65px"
             style="margin-right: 150px;">
      </a>
      <a href="https://www.lbl.gov/">
        <img src="{% static 'img/berkeley.png' %}" height="65px">
      </a>
    </div>
    {#    <hr class="my-0"/>#}
    <div class="my-2"/>
    <div class="d-flex justify-content-around">
      <div>
        <small>
          This work was supported by the Bioenergy Technologies Office of
          the U.S. Department of Energy under Contract No. DE-AC02-05CH11231.
        </small>
      </div>
    </div>
{#    <div class="d-flex justify-content-center text-center">#}
{#      <div>#}
{#        <small>#}
{#          Portions of these results used high performance computing resources#}
{#          located at the Oak Ridge National Laboratory and provided by the#}
{#          Bioenergy Technologies Office of the U.S. Department of Energy.#}
{#        </small>#}
{#      </div>#}
{#    </div>#}
    <div class="my-2"/>
    <div class="d-flex justify-content-around">
      <small>
        Copyright © 2021, All Rights Reserved
      </small>
    </div>
  </div>
  </div>
  {% block footer %}{% endblock %}
</footer>

{#<script#}
{#        src="https://code.jquery.com/jquery-3.4.1.js"#}
{#        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="#}
{#        crossorigin="anonymous">#}
{#</script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"#}
{#        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"#}
{#        crossorigin="anonymous">#}
{#</script>#}
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"#}
{#        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"#}
{#        crossorigin="anonymous">#}
{##}
{#</script>#}

ftf_web/templates/base_flask.html
{% block head %}
{#  <link rel="shortcut icon" href="{{ url_for('static', filename='images/f2f_logo2cropped.png') }}">#}
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-161701269-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-161701269-1');
  </script>
{% endblock %}

{% block styles %}
{#  <link href="{{url_for('static', filename='css/template.css')}}" rel="stylesheet"> <!-- on local computer use .static -->#}
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock %}

{% block title %}
  Feedstock To Function
{% endblock %}

<body>
<div class="content-wrapper">
  {% block navbar %}
    <div class="myheader">
      <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container d-flex h-100">
          <div class="row justify-content-center align-self-center">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar3">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">
                <img id='nav-image' src="{{ url_for('static', filename = 'images/f2f_logo.png') }}">
              </a>
            </div>
            <div id="navbar3" class="navbar-collapse collapse ">
              <ul class="nav navbar-nav navbar-right" id="nav5">
                <li><a href="{{ url_for('exploredatabase') }}"><span class="navtext"> Neat Property Database</span></a></li>
                <li><a href="{{ url_for('predictcost') }}"><span class="navtext">Predict Cost and GHG Footprint</span></a></li>
                <li><a href="{{ url_for('aboutus') }}"><span class="navtext">About</span></a></li>
              </ul>
            </div>
          </div>
          <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
      </nav>

    </div>
  {% endblock %}

  {% block content %}

    <div class="mycontainer">
      {# application content needs to be provided in the app_content block #}
      {% block app_content %}{% endblock %}

    </div>

    {% block footer %}
      <!-- Join Our Team -->
      <div class="container extra-wide cut-off">
        <div class="row">
          <div class="col-sm-12">
            <footer class="footer">
              <div class="container">
                <div class="row text-center">
                  <div class="col-sm-2">
                    <div class="footer-pad">
                      <a href="https://niemeyer-research-group.github.io/" >
{#                        <img src="{{ url_for('static', filename = 'images/osu.png') }}">#}
                      </a>
                    </div>
                  </div>
                  <div class="col-sm-2">
                    <div class="footer-pad">
                      <a href="https://www.lbl.gov/" >
{#                        <img src="{{ url_for('static', filename = 'images/berkeley.png') }}">#}
                      </a>
                    </div>
                  </div>
                  <div class="col-md-4">
                  </div>
                  <div class="col-md-4" id="footer-here">
                    <div class="footer-social-links">
                      <a href="#">
                        <i class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></i>
                      </a>
                      <a href="#">
                        <i class="icoInstagram" title="Instagram"><i class="fa fa-instagram"></i></i>
                      </a>
                      <a href="#">
                        <i class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></i>
                      </a>
                      <a href="#">
                        <i class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></i>
                      </a>
                      <a href="#">
                        <i class="icoYouTube" title="YouTube"><i class="fa fa-youtube"></i></i>
                      </a>
                      </li>
                    </div>
                  </div>
                </div>
              </div>
            </footer>
            <div class="footer-bottom">
              Copyright © 2020, All Rights Reserved
            </div>
          </div>
        </div>
      </div>
    {% endblock %}

  {% endblock %}
</div>
</body>

ftf_web/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div id="carouselExampleIndicators" class="carousel slide"
       data-ride="carousel" data-interval="8000">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0"
          class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner"
         style="padding-left: 20px; padding-right: 20px"
    >
      <div class="carousel-item active">
        {#              <img class="d-block w-100" src="{% static 'img/sucrose_molecule.svg' %}" alt="First slide">#}
        <div class="jumbotron d-block w-100 dark"
             style="padding-top: 20px; padding-bottom: 20px; height: 450px">
          <div class="container">
            {#              <div class="col">#}
            <h1 class="display-4 mt-0">Our Mission</h1>
            <hr class="my-1">
            <p class="light" style="font-size: 18px">
              The Feedstock to Function Tool harnesses the
              power of machine learning to predict properties of
              high-potential
              molecules derived from biomass and evaluates the cost,
              benefits,
              and risk of promising biobased molecules or biofuels to enable
              faster, less expensive bioprocess optimization and scale-up.
            </p>
            <img src="{% static 'img/sucrose_molecule.svg' %}" height="210"
                 style="margin-left: 400px; margin-top:0px"
            >
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="jumbotron d-block w-100 dark"
             style="padding-top: 20px; padding-bottom: 20px; height: 450px">
          <div class="container">
            <h3 class="display-4">Molecule Explorer</h3>
            <hr class="my-4">
            <div class="row">

              <div class="col">
                <p class="light" style="margin-top: 50px; font-size: 20px">
                  Search for molecules in our database and explore their
                  experimental and predicted properties.
                </p>
                <span>
              <a class="btn btn-primary btn-lg mt-5"
                 href="{% url 'chem:search' %}"
                 role="button">
                Launch
              </a>
            </span>
              </div>
              <div class="col">
                <img src="{% static 'img/molec_explorer.png' %}" height="300">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="jumbotron d-block w-100 dark"
             style="padding-top: 20px; padding-bottom: 20px; height: 450px">
          <div class="container">
            <h3 class="display-4">Predict Costs & Emissions</h3>
            <hr class="my-4">
            <div class="row">
              <div class="col">
                <p class="light" style="margin-top: 50px; font-size: 20px">
                  Analyze life-cycle costs and greenhouse gas
                  emissions of bio-produced molecules.
                </p>
                <span>
              <a class="btn btn-primary btn-lg mt-5"
                 href="{% url 'tea_lca:tea_lca_tool' %}"
                 role="button">
                Launch
              </a>
            </span>
              </div>
              <div class="col">
                <img src="{% static 'img/tea_lca_tool.png' %}" height="300">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators"
     role="button" data-slide="prev"
    style="margin-bottom: 150px; margin-top: 250px; height:100px">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators"
     role="button" data-slide="next"
     style="margin-bottom: 150px; margin-top: 250px; height:100px">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>

  <style>
    /* Add an extra .carousel parent class to increase specificity
     avoiding the use of !important flag. */
    .carousel .carousel-indicators li {
      background-color: #fff;
      background-color: rgba(70, 70, 70, 0.25);
    }

    .carousel .carousel-indicators .active {
      background-color: #444;
    }

    .carousel-control-prev-icon,
    .carousel-control-next-icon {
      height: 85px;
      width: 85px;
      outline: black;
      {#background-size: 100%, 100%;#}
      border-radius: 50%;
      border: 0px solid gray;
      background-image: none;
    }

    .carousel-control-next-icon:after {
      content: '>';
      font-size: 50px;
      color: #007bff;
    }

    .carousel-control-prev-icon:after {
      content: '<';
      font-size: 50px;
      color: #007bff;
    }
  </style>
{% endblock %}

ftf_web/templates/password_reset_complete.html
{% extends "base.html" %}
{% block page_content %}

  <div class="d-flex align-items-center justify-content-center info-card-cont">
    <div class="card" style="width: 27rem;">
      <div class="card-header text-center">
        Password Changed
      </div>
      <div class="card-body">
        <p>Your password has successfully been updated.</p>
        <p><a href="{% url 'login' %}">Log in</a> again?</p>
        </p>
      </div>
    </div>
  </div>

{% endblock %}

ftf_web/templates/password_reset_confirm.html
{% extends "base_generic.html" %}

{% block content %}
    {% if validlink %}
        <p>Please enter (and confirm) your new password.</p>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Confirm password:</label>
                    </td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Change my password"/></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Password reset failed</h1>
        <p>The password reset link was invalid, possibly because it has
            already been used. Please request a new password reset.
        </p>
    {% endif %}
{% endblock %}

ftf_web/templates/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://
{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

ftf_web/templates/react_base.html
{% extends "base.html" %}
{% load templatetags %}

{% block content %}
    <div id="react">
        <!-- Contents get replaced by mounted React.Component -->
    </div>
    <script>
      // Escape props to prevent XSS
      // Reference for the source of the json filter:
      // https://gist.github.com/pirate/c18bfe4fd96008ffa0aef25001a2e88f
        window.props = {{props|json}};
        window.react_mount = document.getElementById('react');
    </script>
    <!-- TODO: Use static templatetags here instead -->
    <script src="/static/frontend/{{ component }}"></script>
{% endblock %}